<script>
  import stringHash from '@sindresorhus/string-hash'
  import copy from 'copy-text-to-clipboard'

  import InputBox from '$lib/components/input-box.svelte'
  import KeyValueButton from '$lib/components/key-value-button.svelte'
  import SpinnerInput from '$lib/components/spinner-input.svelte'
  import { addWaitToKeyframes } from '$lib/utils/add-wait-to-keyframes'

  let waitTime = $state('1')
  let className = $state('waitAnimate')
  let duration = $state('2')
  let timingFunction = $state('linear')
  let transformOriginX = $state('50')
  let transformOriginY = $state('50')
  let keyframes = $state(
    '0% {transform: perspective(100px) rotate(0deg) }\n25% {transform: perspective(100px) rotateX(180deg) rotateY(0);}\n50% {transform: perspective(100px) rotateX(180deg) rotateY(180deg);}\n75% {transform: perspective(100px) rotateX(0) rotateY(180deg);}\n100% {transform: perspective(100px) rotateX(0) rotateY(0);}',
  )

  let outputKeyFrames = $derived(
    addWaitToKeyframes(keyframes, duration, waitTime),
  )

  // This acts as a cache buster on chromium-based browsers, and allows changes
  // in the style block to be honoured. The hash must include all vars that can
  // change the animation style.
  let classNameHash = $derived(
    stringHash(
      waitTime +
        className +
        duration +
        timingFunction +
        transformOriginX +
        transformOriginY +
        keyframes,
    ),
  )

  let output = $derived(`/*
Generated by
waitanimate.wstone.uk
*/

.${className} {
  animation: ${className}_${classNameHash} ${
    Number(duration) + Number(waitTime)
  }s ${timingFunction} infinite;
  transform-origin: ${transformOriginX}% ${transformOriginY}%;
}

@keyframes ${className}_${classNameHash} {
${outputKeyFrames}
}`)
</script>

<div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-16">
  <div>
    <div class="mb-4">
      <h4 class="mb-2 text-red-200 font-bold">Class Name</h4>

      <InputBox bind:value={className} />
    </div>

    <div class="grid grid-cols-2 gap-4 mb-4">
      <div>
        <h4 class="mb-2 text-red-200 font-bold">Wait Time</h4>

        <SpinnerInput bind:value={waitTime} isPositiveOnly />

        <div class="text-xs font-bold text-red-300 text-center">Seconds</div>
      </div>

      <div>
        <h4 class="mb-2 text-red-200 font-bold">Animation Duration</h4>

        <SpinnerInput bind:value={duration} isPositiveOnly />

        <div class="text-xs font-bold text-red-300 text-center">Seconds</div>
      </div>
    </div>

    <h4 class="mb-2 text-red-200 font-bold">Timing Function</h4>

    <div class="flex flex-wrap gap-1 mb-4">
      <KeyValueButton bind:key={timingFunction} value="linear" />
      <KeyValueButton bind:key={timingFunction} value="ease" />
      <KeyValueButton bind:key={timingFunction} value="ease-in" />
      <KeyValueButton bind:key={timingFunction} value="ease-out" />
      <KeyValueButton bind:key={timingFunction} value="ease-in-out" />
    </div>

    <div class="grid grid-cols-2 gap-4 mb-4">
      <div>
        <h4 class="mb-2 text-red-200 font-bold">Transform Origin X</h4>

        <SpinnerInput bind:value={transformOriginX} />

        <div class="text-xs font-bold text-red-300 text-center">%</div>
      </div>

      <div>
        <h4 class="mb-2 text-red-200 font-bold">Transform Origin Y</h4>

        <SpinnerInput bind:value={transformOriginY} />

        <div class="text-xs font-bold text-red-300 text-center">%</div>
      </div>
    </div>

    <h4 class="mb-2 text-red-200 font-bold">Keyframes</h4>

    <textarea
      bind:value={keyframes}
      class="font-mono text-black text-sm w-full p-4 shadow-inner border-4
      border-black bg-white overflow-auto whitespace-pre"
      rows="5"
    ></textarea>
  </div>

  <div class="relative">
    <div class="absolute right-0 pl-4 pb-4 bg-red-800">
      <div class="w-32 p-4 text-center bg-red-900 text-white rounded shadow-md">
        <span class="inline-block font-title text-6xl {className}">!</span>
      </div>
    </div>

    <h4 class="mb-2 text-red-200 font-bold">Calculated Keyframes</h4>

    <div
      class="font-mono bg-red-900 text-white p-4 mb-4 rounded overflow-auto
      text-xs"
    >
      <!-- eslint-disable-next-line svelte/no-at-html-tags -->
      {@html `<${'style'} class="block whitespace-pre">${output}</style>`}
    </div>

    <button
      onclick={() => copy(output)}
      type="button"
      class="border-4 border-black h-12 text-lg flex items-center justify-center
      font-bold bg-black text-white px-2 ml-auto hover:bg-red-900"
    >
      Copy To Clipboard
    </button>
  </div>
</div>
